### PR TITLE
fix(fargate): ensure fargate profile name is valid

### LINKED ISSUE #426: Error: "The fargate profile name starts with the reserved prefix: 'eks-'."
Attempted to deploy this:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as awsx from "@pulumi/awsx";
import * as eks from "@pulumi/eks";

const vpc = new awsx.ec2.Vpc("workshop-vpc", {});

const cluster = new eks.Cluster("eks", {
    vpcId: vpc.id,
    privateSubnetIds: vpc.privateSubnetIds,
    publicSubnetIds: vpc.publicSubnetIds,
    fargate: true,
});

export const kubeconfig = cluster.kubeconfig;
```

And 15 minutes later it failed with this:

```
  aws:eks:FargateProfile (eks-fargateProfile):
    error: error creating EKS Fargate Profile (eks-eksCluster-d4112d4:eks-fargateProfile-b871e08): InvalidParameterException: The fargate profile name starts with the reserved prefix: 'eks-'.
    {
      RespMetadata: {
        StatusCode: 400,
        RequestID: "92ac5d87-7191-46a1-9c49-98089cabb361"
      },
      Message_: "The fargate profile name starts with the reserved prefix: 'eks-'."
    }
```

We should be able to catch this earlier and either make it work or provide a better errror.

Also unfortunate as this is very difficult to "fix" without fully replacing the cluster.

### PR DESCRIPTION
**Pull request by metral**
### Proposed changes

fix(fargate): ensure fargate profile name is valid

### Related issues (optional)

Fixes #426

### CODE REVIEW

File: nodejs/eks/cluster.ts [hunk 1]
```diff
@@ -340,6 +340,20 @@ export function createCore(name: string, args: ClusterOptions, parent: pulumi.Co
         throw new Error("Setting nodeGroupOptions, and any set of singular node group option(s) on the cluster, is mutually exclusive. Choose a single approach.");
     }
 
+    // Check if the cluster name provided or autoname used starts with 'eks-'.
+    // The cluster name is used for the fargate profile name, and we must
+    // ensure `eks-` is not used in either naming option, as AWS considers it
+    // a reserved prefix and will fail the fargate profile creation.
+    if (args.fargate) {
+        const nameToCheck = args.name || name.concat("-");
```
Comment (lblackstone) [inline nodejs/eks/cluster.ts:348]: Do you  need `pulumi.concat` here? I don't think the basic concat works on some Inputs

Comment (metral) [reply nodejs/eks/cluster.ts:348]: The `name` that is being checked and concatenated is from the Cluster ctor, which is of type `string`. What inputs do you think would not work?

https://github.com/pulumi/pulumi-eks/blob/7dd282665e72bf8af3f292c1354bedc4be2542e7/nodejs/eks/cluster.ts#L1281-L1301

Comment (lblackstone) [reply nodejs/eks/cluster.ts:348]: Oops, you're right. I misread it as `args.name`

File: nodejs/eks/cluster.ts [hunk 2]
```diff
@@ -340,6 +340,20 @@ export function createCore(name: string, args: ClusterOptions, parent: pulumi.Co
...
+        const profileNameRegex = new RegExp("^" + "eks-", "i"); // starts with (^) 'eks-', (i)gnore casing
+        pulumi.output(nameToCheck).apply(n => {
+            if (profileNameRegex.test(n)) {
+                throw new Error(`The fargate profile name uses the cluster name, and the name provided will use the reserved AWS prefix that is not allowed: 'eks-'. Choose an alternate name`);
+            }
+        });
```
Comment (lukehoban) [inline nodejs/eks/cluster.ts:354]: Does this approach of asyncronously throwing an error that isn't "handled" anywhere actually work?  I wouldn't have thought so.  This code will continue on executing the body of this function, and only once done with all the synchronous work of constructing these resources will it come back to asynchronously execute this callback.  And then that promise/output will fail with an error, but nothing is listening to it (it's not an input to anything else) - so I think it will just get ignored.  It may finally get picked up by Node's unhandled promise rejection handler a couple turns later - but I suspect that (a) the experience won't be good and (b) other resources may well get created ahead of this.  

Relatedly - can't we just construct a name that will actually work instead of trying to error?  That is can't we just change this line:

```
fargateProfile = new aws.eks.FargateProfile(`${name}-fargateProfile`, {
```

To check if `name` is `eks` and if so use an `_` instead of `-` or something like that (or just drop the `-`)?

File: nodejs/eks/cluster.ts [hunk 3]
```diff
@@ -658,7 +658,19 @@ export function createCore(name: string, args: ClusterOptions, parent: pulumi.Co
...
+        const profileNameRegex = new RegExp("^" + reservedAwsPrefix + "-", "i"); // starts with (^) 'eks-', (i)gnore casing
+        if (fargateProfileName === reservedAwsPrefix || profileNameRegex.test(name)) {
+            fargateProfileName = fargateProfileName.replace("-", "_");
+            fargateProfileName = `${fargateProfileName}fargateProfile`;
+        } else {
+            // default, and to maintain backwards compat for existing cluster fargate profiles.
+            fargateProfileName = `${fargateProfileName}-fargateProfile`;
+        }
+
+        fargateProfile = new aws.eks.FargateProfile(`${fargateProfileName}`, {
```
Comment (lblackstone) [inline nodejs/eks/cluster.ts:673]:
```suggestion
        fargateProfile = new aws.eks.FargateProfile(fargateProfileName, {
```
