### PR TITLE
Model storageclasses as a map in schema

### LINKED ISSUE #523: Unable to pass args for storage class to eks cluster using Python
## Unable To Pass args for Storage Class

While I am trying to create eks cluster using python, I was able to create cluster but when I tried to customize the storage class arguments. I am seeing a lot of errors in creation.
 
## Error:

     Type                                             Name                                           Status                  Info
 +   pulumi:pulumi:Stack                              abhi-pulumi-dev                                **creating failed**     1 error
 +   ├─ aws:ec2:Vpc                                   eks-vpc                                        created                 
 +   ├─ aws:iam:Role                                  eks-iam-role                                   created                 
 +   ├─ aws:iam:Role                                  ec2-nodegroup-iam-role                         created                 
 +   ├─ aws:iam:RolePolicyAttachment                  eks-service-policy-attachment                  created                 
 +   ├─ aws:iam:RolePolicyAttachment                  eks-cluster-policy-attachment                  created                 
 +   ├─ aws:iam:RolePolicyAttachment                  eks-workernode-policy-attachment               created                 
 +   ├─ aws:iam:RolePolicyAttachment                  eks-cni-policy-attachment                      created                 
 +   ├─ aws:iam:RolePolicyAttachment                  ec2-container-ro-policy-attachment             created                 
 +   ├─ aws:iam:InstanceProfile                       testProfile                                    created                 
 +   ├─ aws:ec2:InternetGateway                       vpc-ig                                         created                 
 +   ├─ aws:ec2:Subnet                                vpc-subnet-us-west-2a                          created                 
 +   ├─ aws:ec2:Subnet                                vpc-subnet-us-west-2b                          created                 
 +   ├─ aws:ec2:Subnet                                vpc-subnet-us-west-2c                          created                 
 +   ├─ aws:ec2:Subnet                                vpc-subnet-us-west-2d                          created                 
 +   ├─ aws:ec2:SecurityGroup                         eks-cluster-sg                                 created                 
 +   ├─ aws:ec2:RouteTable                            vpc-route-table                                created                 
 +   ├─ eks:index:Cluster                             eks-cluster                                    created                 
 +   │  ├─ eks:index:ServiceRole                      eks-cluster-eksRole                            created                 
 +   │  │  ├─ aws:iam:Role                            eks-cluster-eksRole-role                       created                 
 +   │  │  ├─ aws:iam:RolePolicyAttachment            eks-cluster-eksRole-90eb1c99                   created                 
 +   │  │  └─ aws:iam:RolePolicyAttachment            eks-cluster-eksRole-4b490823                   created                 
 +   │  ├─ eks:index:ServiceRole                      eks-cluster-instanceRole                       created                 
 +   │  │  ├─ aws:iam:Role                            eks-cluster-instanceRole-role                  created                 
 +   │  │  ├─ aws:iam:RolePolicyAttachment            eks-cluster-instanceRole-03516f97              created                 
 +   │  │  ├─ aws:iam:RolePolicyAttachment            eks-cluster-instanceRole-e1b295bd              created                 
 +   │  │  └─ aws:iam:RolePolicyAttachment            eks-cluster-instanceRole-3eb088f2              created                 
 +   │  ├─ eks:index:RandomSuffix                     eks-cluster-cfnStackName                       created                 
 +   │  ├─ aws:ec2:SecurityGroup                      eks-cluster-eksClusterSecurityGroup            created                 
 +   │  ├─ aws:ec2:SecurityGroupRule                  eks-cluster-eksClusterInternetEgressRule       created                 
 +   │  ├─ aws:eks:Cluster                            eks-cluster-eksCluster                         created                 
 +   │  ├─ aws:ec2:SecurityGroup                      eks-cluster-nodeSecurityGroup                  created                 
 +   │  ├─ eks:index:VpcCni                           eks-cluster-vpc-cni                            created                 
 +   │  ├─ pulumi:providers:kubernetes                eks-cluster-eks-k8s                            created                 
 +   │  ├─ kubernetes:storage.k8s.io/v1:StorageClass  eks-cluster-toJSON                             **creating failed**     1 error
 +   │  ├─ kubernetes:storage.k8s.io/v1:StorageClass  eks-cluster-resources                          created                 
 +   │  ├─ kubernetes:storage.k8s.io/v1:StorageClass  eks-cluster-__pulumiOutput                     **creating failed**     1 error
 +   │  ├─ kubernetes:storage.k8s.io/v1:StorageClass  eks-cluster-promise                            created                 
 +   │  ├─ kubernetes:storage.k8s.io/v1:StorageClass  eks-cluster-toString                           **creating failed**     1 error
 +   │  ├─ kubernetes:storage.k8s.io/v1:StorageClass  eks-cluster-isSecret                           **creating failed**     1 error
 +   │  ├─ kubernetes:core/v1:ConfigMap               eks-cluster-nodeAccess                         created                 
 +   │  ├─ kubernetes:storage.k8s.io/v1:StorageClass  eks-cluster-allResources                       **creating failed**     1 error
 +   │  ├─ kubernetes:storage.k8s.io/v1:StorageClass  eks-cluster-isKnown                            **creating failed**     1 error
 +   │  ├─ aws:ec2:SecurityGroupRule                  eks-cluster-eksClusterIngressRule              created                 
 +   │  ├─ aws:ec2:SecurityGroupRule                  eks-cluster-eksNodeClusterIngressRule          created                 
 +   │  ├─ aws:ec2:SecurityGroupRule                  eks-cluster-eksNodeInternetEgressRule          created                 
 +   │  ├─ aws:ec2:SecurityGroupRule                  eks-cluster-eksNodeIngressRule                 created                 
 +   │  └─ aws:ec2:SecurityGroupRule                  eks-cluster-eksExtApiServerClusterIngressRule  created                 
 +   ├─ aws:ec2:RouteTableAssociation                 vpc-route-table-assoc-us-west-2a               created                 
 +   ├─ aws:ec2:RouteTableAssociation                 vpc-route-table-assoc-us-west-2b               created                 
 +   ├─ aws:ec2:RouteTableAssociation                 vpc-route-table-assoc-us-west-2c               created                 
 +   └─ aws:ec2:RouteTableAssociation                 vpc-route-table-assoc-us-west-2d               created                 
 
Diagnostics:
  pulumi:pulumi:Stack (abhi-pulumi-dev):
    error: update failed
 
  kubernetes:storage.k8s.io/v1:StorageClass (eks-cluster-allResources):
    error: resource eks-cluster-allResources-x90cn60u was not successfully created by the Kubernetes API server : StorageClass.storage.k8s.io "eks-cluster-allResources-x90cn60u" is invalid: metadata.name: Invalid value: "eks-cluster-allResources-x90cn60u": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
 
  kubernetes:storage.k8s.io/v1:StorageClass (eks-cluster-isSecret):
    error: resource eks-cluster-isSecret-ohj6lo6p was not successfully created by the Kubernetes API server : StorageClass.storage.k8s.io "eks-cluster-isSecret-ohj6lo6p" is invalid: metadata.name: Invalid value: "eks-cluster-isSecret-ohj6lo6p": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
 
  kubernetes:storage.k8s.io/v1:StorageClass (eks-cluster-__pulumiOutput):
    error: resource eks-cluster-__pulumiOutput-jlna8sco was not successfully created by the Kubernetes API server : StorageClass.storage.k8s.io "eks-cluster-__pulumiOutput-jlna8sco" is invalid: metadata.name: Invalid value: "eks-cluster-__pulumiOutput-jlna8sco": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
 
  kubernetes:storage.k8s.io/v1:StorageClass (eks-cluster-toString):
    error: resource eks-cluster-toString-i5n6h9zx was not successfully created by the Kubernetes API server : StorageClass.storage.k8s.io "eks-cluster-toString-i5n6h9zx" is invalid: metadata.name: Invalid value: "eks-cluster-toString-i5n6h9zx": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
 
  kubernetes:storage.k8s.io/v1:StorageClass (eks-cluster-isKnown):
    error: resource eks-cluster-isKnown-qiu6ebhh was not successfully created by the Kubernetes API server : StorageClass.storage.k8s.io "eks-cluster-isKnown-qiu6ebhh" is invalid: metadata.name: Invalid value: "eks-cluster-isKnown-qiu6ebhh": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
 
  kubernetes:storage.k8s.io/v1:StorageClass (eks-cluster-toJSON):
    error: resource eks-cluster-toJSON-qwizj94p was not successfully created by the Kubernetes API server : StorageClass.storage.k8s.io "eks-cluster-toJSON-qwizj94p" is invalid: metadata.name: Invalid value: "eks-cluster-toJSON-qwizj94p": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

##

If we clearly observe the section where its creating the storage class, there are lot of components with storage class are getting created.

# Inputs:

eks_cluster = k8s.Cluster('eks-cluster',
    vpc_id=vpc.id,
    public_subnet_ids=subnet_ids,
    desired_capacity=3,
    public_access_cidrs=['0.0.0.0/0'],
    min_size=2,
    max_size=3,
    instance_type='t3.micro',
    instance_profile_name=testProfile.id,
    #cluster_security_group=eks_security_group.id,
    storage_classes=[k8s.StorageClassArgs(type='gp2', allow_volume_expansion=True, default=True, encrypted=True,)],
    role_mappings=[k8s.RoleMappingArgs(
        groups=['system:masters'],
        role_arn='arn:aws:iam::xxxx:role/role-app',
        username='pulumi:admin-usr')],
    enabled_cluster_log_types=[
        "api",
        "audit",
        "authenticator",
    ],)

image

### PR DESCRIPTION
**Pull request by viveklak**
Fix #523 

eks component resource seems to expect the storageclasses specification to be a map keyed by a string. Updated the schema to reflect this.

### CODE REVIEW

File: provider/cmd/pulumi-gen-eks/main.go [hunk 1]
```diff
@@ -377,10 +377,9 @@ func generateSchema() schema.PackageSpec {
 					},
 					"storageClasses": {
 						TypeSpec: schema.TypeSpec{
-							Type: "string", // TODO: EBSVolumeType enum "io1" | "gp2" | "sc1" | "st1"
 							OneOf: []schema.TypeSpec{
 								{Type: "string"},
```
Comment (justinvp) [inline provider/cmd/pulumi-gen-eks/main.go:381]: Mind adding a comment about the EBSVolumenType enum here?

**Review by justinvp — APPROVED** [review]
LGTM
