### PR TITLE
Fix issue in OIDC getThumbprint helper function

### LINKED ISSUE #345: Occasional issue with `createOidcProvider: true`
### Problem description

I am using the new `createOidcProvider: true` option.  It is failing roughly 50% of the time with the error below.

This only happens running `pulumi preview/apply` some of the time.  After a failure, a subsequent run may have no issue at all.

### Errors & Logs
```
Diagnostics:
pulumi:pulumi:Stack (infrastructure-clusters):
  Method handler getSchema for /pulumirpc.ResourceProvider/GetSchema expected but not provided

  Method handler getSchema for /pulumirpc.ResourceProvider/GetSchema expected but not provided

  error: Running program '/home/jenkins/agent/workspace/INFURA_infrastructure_oidc' failed with an unhandled exception:
  TypeError: Cannot read property 'fingerprint' of undefined
      at TLSSocket.<anonymous> (/home/jenkins/agent/workspace/INFURA_infrastructure_oidc/node_modules/@pulumi/cert-thumprint.ts:77:82)
      at TLSSocket.emit (events.js:321:20)
      at TLSSocket.EventEmitter.emit (domain.js:485:12)
      at TLSSocket.onConnectSecure (_tls_wrap.js:1504:10)
      at TLSSocket.emit (events.js:321:20)
      at TLSSocket.EventEmitter.emit (domain.js:485:12)
      at TLSSocket._finishInit (_tls_wrap.js:918:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:688:12)
```

### Affected product version(s)
`"@pulumi/eks": "^0.18.23"`

### Reproducing the issue

Occurs occasionally in stack with
```
const cluster = new eks.Cluster('test', {
    deployDashboard: false,
    createOidcProvider: true,
});
```

### PR DESCRIPTION
**Pull request by timmyers**
### Proposed changes

Fixes an issue in the OIDC provisioning `getThumbprint` helper function.  It is possible for HTTPS sessions to be cached between calls to this.  When this happens, the SSL cert is not available.  Allow no caching so we can always get the cert.

This probably only caused issues when multiple clusters were in the stack.

### Related issues

Fixes #345

### CODE REVIEW

**Comment by timmyers** [comment]
Woops totally missed the existing headers.

File: nodejs/eks/cert-thumprint.ts [hunk 1]
```diff
@@ -67,6 +67,7 @@ async function getThumbprint(issuerUrl: string, retriesLeft: number, interval: n
                 hostname: issuerUrl,
                 port: 443,
                 rejectUnauthorized: false,
+                agent: new https.Agent({ maxCachedSessions: 0 }),
```
Comment (lukehoban) [inline nodejs/eks/cert-thumprint.ts]: That’s pretty subtle! :smile: Possibly a comment here on why we need to set this?
