### PR TITLE
Fix js-yaml dependency changes in pulumi/k8s

### LINKED ISSUE #325: Removal of js-yaml and YAML invoke changes in pulumi/k8s breaks withUpdate tests, and tests that load YAML
### Problem description

withUpdate tests, and examples that load yaml (e.g. `examples/clusters` and `examples/tests/replace-secgroup` which deploy the YAML dashboard) are failing.

The withUpdate tests can't find the `js-yaml` module using the latest `pulumi/eks` release (0.18.19), as the latest release of `pulumi/k8s` (1.5.1) no longer vendors it, and `pulumi/eks` did not specifically vendor it:

```
Error: Cannot find module 'js-yaml'
```

The examples that load YAML through the dashboard hit the following error possibly due to changes in `yamlLoadAll` in the commit ref below:

```
[ xamples/tests/replace-secgroup ]     TypeError: Cannot read property 'map' of undefined
[ xamples/tests/replace-secgroup ]         at config.objs.then.configObjs (/opt/pulumi/node_modules/@pulumi/eks/node_modules/@pulumi/kubernetes/yaml/yaml.js:180:14
```

### Errors & Logs

[Travis CI Run Logs](https://travis-ci.com/pulumi/pulumi-eks/builds/147993117)

Ref: pulumi/k8s [commit](https://github.com/pulumi/pulumi-kubernetes/commit/4b1bc4ff90ff22c030eebed86b4b7cd02db5c4da#diff-c6beee34c53489be29806bf23383af5aL17-L18) where js-yaml was removed, and in the same commit where invoke [yamlLoadAll](https://github.com/pulumi/pulumi-kubernetes/commit/4b1bc4ff90ff22c030eebed86b4b7cd02db5c4da#diff-e796470dbaaefe7239d307d5d9777483R124-R136) changed.

### PR DESCRIPTION
**Pull request by metral**
### Proposed changes

- Vendor js-yaml in `pulumi/eks` after it was removed from `pulumi/k8s`
- Pin pulumi/k8s to ^1.5.3
- Temporarily disable `withUpdate` tests to cut a new pulumi/eks release. These tests use `latest` of pulumi/eks, which depended on pulumi/k8s for js-yaml, so they will always fail until we cut a new release of eks that does vendor it.

Fixes #325

### CODE REVIEW

File: nodejs/eks/dashboard.ts [hunk 1]
```diff
@@ -21,14 +21,8 @@ export interface DashboardOptions {}
...
     // Deploy the latest version of the k8s dashboard.
-    const dashboardYaml = [
-        path.join(__dirname, "dashboard", "kubernetes-dashboard.yaml"),
-        path.join(__dirname, "dashboard", "heapster.yaml"),
-        path.join(__dirname, "dashboard", "influxdb.yaml"),
-        path.join(__dirname, "dashboard", "heapster-rbac.yaml"),
-    ].map(filePath => fs.readFileSync(filePath).toString());
     const dashboard = new k8s.yaml.ConfigGroup(`${name}-dashboard`, {
-        yaml: dashboardYaml,
+        files: "./dashboard/*",
```
Comment (lblackstone) [inline nodejs/eks/dashboard.ts]: Actually, I'm not sure if this will work for Windows. May need to do a `path.join` here

Comment (metral) [reply nodejs/eks/dashboard.ts]: `files: path.join(__dirname, "dashboard"` does not work. Results in the same error. any thoughts?

Comment (lukehoban) [reply nodejs/eks/dashboard.ts]: Why do we need to make a change here?  How is this related to js-yaml?

Comment (metral) [reply nodejs/eks/dashboard.ts]: Certain tests are hitting the following, possibly due to yaml invoking
```
[ xamples/tests/replace-secgroup ]     TypeError: Cannot read property 'map' of undefined
[ xamples/tests/replace-secgroup ]         at config.objs.then.configObjs (/opt/pulumi/node_modules/@pulumi/eks/node_modules/@pulumi/kubernetes/yaml/yaml.js:180:14
```

The theory is that this is occurring to tests that load YAML (e.g. that deploy the dashboard) with a recent change in pulumi/k8s.

See https://github.com/pulumi/pulumi-eks/issues/325 for more info
