### PR TITLE
fix(oidc): use thumbprint of the intermediate root CA

### LINKED ISSUE #342: Service Account token for Pod IAM role is misconfigured with incorrect OIDC provider CA cert thumbprint
### Problem description

The projected service account token used to assume an IAM role from a Pod is not properly configured with the correct OIDC provider root CA thumbprint.

There's a mismatch in the thumbprint expected by AWS when issuing the temporary credentials for the Pod

### Errors & Logs

```
time="2020-03-04T02:57:11Z" level=error msg="WebIdentityErr: failed to retrieve credentials\ncaused by: 
InvalidIdentityToken: OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint\n\tstatus code: 400, 
request id: 8586235f-772e-4e0b-ba22-00b99de7905e"
```

### Affected product version(s)

v0.18.22

### PR DESCRIPTION
**Pull request by metral**
### Proposed changes

- fix(oidc): use thumbprint of the intermediate root CA
- test(oidc): add s3 example to test service account IAM token works
- test(utils): update smoketest to mark succeeded pods like jobs, as ready
- test(utils): bump req wait time from 5m -> 10m to avoid early timeouts
- test(oidc): use default ng as pods fail smoketest if mgdng is not up yet

### Related issues (optional)

Fixes #342

### CODE REVIEW

File: nodejs/eks/cert-thumprint.ts [hunk 1]
```diff
@@ -40,10 +40,12 @@ export function getIssuerCAThumbprint(issuerUrl: pulumi.Output<string>): pulumi.
 // Find the root CA cert in a chain of certs.
 function findCACertificate(certificate: tls.DetailedPeerCertificate): tls.DetailedPeerCertificate {
     let cert = certificate;
+    let issuerCert = cert?.issuerCertificate;
     for (; cert?.issuerCertificate?.fingerprint !== cert?.fingerprint;) {
+        issuerCert = cert;
```
Comment (lblackstone) [inline nodejs/eks/cert-thumprint.ts]: I'm not convinced this code is right. It looks like the goal is for `cert.issuerCertificate` to match `cert.fingerprint`?

Comment (metral) [reply nodejs/eks/cert-thumprint.ts]: `cert` and `issuerCert` are placeholders that get overwritten as the chain of certs is traversed. 

The idea is to continuously view the fingerprint for the current cert's issuerCert. once they are equal, that means we have reached the root CA, and we return what was stored in `issuerCert`.

It is the non-recursive implementation used in [CDK](https://github.com/aws/aws-cdk/pull/6062/files#diff-0c88b2ccea9d77dbb7ac2285fd5f63afR114-R122)

Comment (lblackstone) [reply nodejs/eks/cert-thumprint.ts]: How about the following instead?

```ts
let cert = certificate;
while (cert.issuerCert && cert.issuerCert.fingerprint !== cert?.fingerprint) {
    cert = cert.issuerCert;
}
return cert;
```

[Playground Link](https://www.typescriptlang.org/v2/en/play?#code/C4TwDgpgBAwhBOwoF4oG8CwAoKuoDMBLAOwHMEx4TgB+ALigGdgqzs8pDHGBXBORPVgJg2AL7YAxgHtizAtOkMBSVJhx4iZCq2AMARAEN9AGnZ4uvfiIbqOHLeXiVqBgEanz9ztz7wVtl7emiROLsR6UPqSnhreEnFQCQnYADYQSJI2wogoCtIA3NgA7gAWhOlQABRZiAB0ln4qUABkLVC1wA2+1vWOOtRQAITIqJ00df3OugCU6EGdeZ3dVv4iRVgJMnLS6XWp0qRVAOQASopIU+GRx1AA1B0ik6EDETNAA)

Comment (metral) [reply nodejs/eks/cert-thumprint.ts]: Turns out we have to return the intermediate root CA cert, not the trusted root CA to configure the OIDC provider.

The intermediate root CA cert is the _second to last_ cert in the full chain.

See the updated [changes](https://github.com/pulumi/pulumi-eks/pull/343/files) for more info and links.

**Comment by metral** [comment]
Feedback has been addressed. PTAL @lblackstone
