### PR TITLE
Wait for cluster endpoint

### LINKED ISSUE #65: Failures to kubectl apply
We periodically see CI failures due to the below, and have also heard user reports of seeing similar.  We should figure out what is needed to be robust against this:

```
[ ks/nodejs/eks/examples/cluster ]   pulumi-nodejs:dynamic:Resource (cluster2-vpc-cni):
[ ks/nodejs/eks/examples/cluster ]     error: Plan apply failed: Command failed: kubectl apply -f /tmp/tmp-12841ugyvSLxyVH46.tmp
[ ks/nodejs/eks/examples/cluster ]     error: unable to recognize "/tmp/tmp-12841ugyvSLxyVH46.tmp": Get https://AA28F18B717D67BED6FEC1BFB8B2C64F.sk1.eu-west-1.eks.amazonaws.com/api?timeout=32s: dial tcp 54.154.206.100:443: i/o timeout
```

### PR DESCRIPTION
**Pull request by lukehoban**
Wait for up to 300 seconds for cluster endpoint to be reachable.

Fixes #65.

### CODE REVIEW

File: nodejs/eks/cluster.ts [hunk 1]
```diff
@@ -160,10 +162,34 @@ export function createCore(name: string, args: ClusterOptions, parent: pulumi.Co
         enabledClusterLogTypes: args.enabledClusterLogTypes,
     }, { parent: parent });
 
+    // Instead of using the kubeconfig directly, we also add a wait of up to 5 minutes or until we
+    // can reach the API server to the Output that provides access to the kubeconfig string so that
```
Comment (metral) [inline nodejs/eks/cluster.ts]:
```suggestion
    // can reach the API server for the Output that provides access to the kubeconfig string so that
```

File: nodejs/eks/cluster.ts [hunk 2]
```diff
@@ -160,10 +162,34 @@ export function createCore(name: string, args: ClusterOptions, parent: pulumi.Co
...
+    // there is time for the target cluster API server to become completely available.  Ideally we
```
Comment (metral) [inline nodejs/eks/cluster.ts]:
```suggestion
    // there is time for the cluster API server to become completely available.  Ideally we
```

**Comment by icereed** [comment]
Hi there, could it be that this polling is not respecting the http_proxy setting?

**Comment by metral** [comment]
@icereed proxy support is being tracked in https://github.com/pulumi/pulumi-eks/issues/350
