### PR TITLE
Relax validations on eks.Cluster instance_roles

### LINKED ISSUE #1220: Cluster with auth mode `API` can not be created with workaround that prevents instance role creation
### What happened?

Customer tried to create an `eks.Cluster` with authentication mode `API` and applying the suggested workaround from [#1176](https://github.com/pulumi/pulumi-eks/issues/1176#issuecomment-2141765544). In this setup, `pulumi preview` returns a Python stacktrace:

```
  pulumi:pulumi:Stack (5423-ringo):
    Error: The 'instanceRoles' property is not supported when 'authenticationMode' is set to 'API'.: Error: The 'instanceRoles' property is not supported when 'authenticationMode' is set to 'API'.
        at /snapshot/eks/bin/authenticationMode.js:39:23
        at Array.forEach (<anonymous>)
        at validateAuthenticationMode (/snapshot/eks/bin/authenticationMode.js:37:33)
        at createCore (/snapshot/eks/bin/cluster.js:209:57)
        at createCluster (/snapshot/eks/bin/cluster.js:846:18)
        at new ClusterInternal (/snapshot/eks/bin/cluster.js:929:25)
        at Object.construct (/snapshot/eks/bin/cmd/provider/cluster.js:21:29)
        at Provider.construct (/snapshot/eks/bin/cmd/provider/index.js:133:24)
        at Server.<anonymous> (/snapshot/eks/node_modules/@pulumi/pulumi/provider/server.js:315:52)
        at Generator.next (<anonymous>)

    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/ringods/Projects/pulumi-customers/customer-engineering/customer-support/5423/.venv/lib/python3.12/site-packages/pulumi/runtime/resource.py", line 1010, in do_rpc_call
        return monitor.RegisterResource(req)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/ringods/Projects/pulumi-customers/customer-engineering/customer-support/5423/.venv/lib/python3.12/site-packages/grpc/_channel.py", line 1160, in __call__
        return _end_unary_response_blocking(state, call, False, None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/ringods/Projects/pulumi-customers/customer-engineering/customer-support/5423/.venv/lib/python3.12/site-packages/grpc/_channel.py", line 1003, in _end_unary_response_blocking
        raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "The 'instanceRoles' property is not supported when 'authenticationMode' is set to 'API'."
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"The \'instanceRoles\' property is not supported when \'authenticationMode\' is set to \'API\'.", grpc_status:2, created_time:"2024-07-01T13:34:24.79352+02:00"}"
    >
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 191, in <module>
        loop.run_until_complete(coro)
      File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
        return future.result()
               ^^^^^^^^^^^^^^^
      File "/Users/ringods/Projects/pulumi-customers/customer-engineering/customer-support/5423/.venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 138, in run_in_stack
        await run_pulumi_func(run)
      File "/Users/ringods/Projects/pulumi-customers/customer-engineering/customer-support/5423/.venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 52, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/ringods/Projects/pulumi-customers/customer-engineering/customer-support/5423/.venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 114, in wait_for_rpcs
        await task
      File "/Users/ringods/Projects/pulumi-customers/customer-engineering/customer-support/5423/.venv/lib/python3.12/site-packages/pulumi/runtime/resource.py", line 1015, in do_register
        resp = await asyncio.get_event_loop().run_in_executor(None, do_rpc_call)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/ringods/Projects/pulumi-customers/customer-engineering/customer-support/5423/.venv/lib/python3.12/site-packages/pulumi/runtime/resource.py", line 1012, in do_rpc_call
        handle_grpc_error(exn)
      File "/Users/ringods/Projects/pulumi-customers/customer-engineering/customer-support/5423/.venv/lib/python3.12/site-packages/pulumi/runtime/settings.py", line 307, in handle_grpc_error
        raise grpc_error_to_exception(exn)
    Exception: The 'instanceRoles' property is not supported when 'authenticationMode' is set to 'API'.
```

Setting `instance_roles=[]` is used to prevent creation of the following resources:

```
 +      ├─ eks:index:ServiceRole                   zd-5423-instanceRole                       create     
 +      │  ├─ aws:iam:RolePolicyAttachment         zd-5423-instanceRole-3eb088f2              create     
 +      │  ├─ aws:iam:Role                         zd-5423-instanceRole-role                  create     
 +      │  ├─ aws:iam:RolePolicyAttachment         zd-5423-instanceRole-e1b295bd              create     
 +      │  └─ aws:iam:RolePolicyAttachment         zd-5423-instanceRole-03516f97              create     
```

The only workaround for this issue is removing the other workaround and allowing the creation of these unnecessary resources.

### Example

```python
import pulumi
import pulumi_aws as aws
import pulumi_awsx as awsx
import pulumi_eks as eks

vpc = awsx.ec2.Vpc("vpc")

cluster = eks.Cluster(
    "zd-5423",
    vpc_id=vpc.vpc_id,
    public_subnet_ids=vpc.public_subnet_ids,
    private_subnet_ids=vpc.private_subnet_ids,
    authentication_mode=eks.AuthenticationMode.API,
    skip_default_node_group=True,
    instance_roles=[],
    use_default_vpc_cni=False,
)
```

### Output of `pulumi about`

```
pulumi about
CLI          
Version      3.121.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.41.0
resource  awsx        2.12.3
resource  docker      4.5.4
resource  eks         2.7.1
resource  kubernetes  4.13.1
language  python      unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in python: executable='/Users/ringods/Projects/pulumi-customers/customer-engineering/customer-support/5423/.venv/bin/python' version='3.12.4'

Current Stack: team-ce/5423/ringo

Found no resources associated with team-ce/ringo

Found no pending operations associated with team-ce/ringo

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/v-ringo-pulumi-corp
User           v-ringo-pulumi-corp
Organizations  v-ringo-pulumi-corp, team-ce
Token type     personal

Dependencies:
NAME         VERSION
pip          24.0
pulumi_awsx  2.12.3
pulumi_eks   2.7.1

Pulumi locates its logs in /var/folders/yq/10j1hf8s1ks9f23yxrdbbbb40000gn/T/ by default
non-package-mode-py3.12
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by t0yv0**
### Proposed changes

This change allows a program to set empty `instance_roles=[]` on an eks.Cluster with custom `authentication_mode` without triggering a warning on these properties being incompatible.

roleMappings and userMappings are treated symmetrically.

### Related issues (optional)

Fixes #1220

### CODE REVIEW

**Comment by t0yv0** [comment]
I've confirmed this fixes preview of the following program. Checking if it fixes `pulumi up` as well.

```python

import pulumi
import pulumi_aws as aws
import pulumi_awsx as awsx
import pulumi_eks as eks

vpc = awsx.ec2.Vpc("vpc")

cluster = eks.Cluster(
    "zd-5423",
    vpc_id=vpc.vpc_id,
    public_subnet_ids=vpc.public_subnet_ids,
    private_subnet_ids=vpc.private_subnet_ids,
    authentication_mode=eks.AuthenticationMode.API,
    skip_default_node_group=True,
    instance_roles=[],
    use_default_vpc_cni=False,
)

```

File: nodejs/eks/authenticationMode.ts [hunk 1]
```diff
@@ -43,7 +43,13 @@ export function validateAuthenticationMode(args: ClusterOptions) {
 
     if (!supportsConfigMap(args.authenticationMode)) {
         configMapOnlyProperties.forEach((prop) => {
-            if (args[prop]) {
+            const arg: any = args[prop];
+            if (arg) {
+                // Permit empty instanceRoles as a specialCase.
+                if ((arg.length === 0) && prop === "instanceRoles") {
```
Comment (flostadler) [inline nodejs/eks/authenticationMode.ts:49]: instanceRoles is of type `pulumi.Input<pulumi.Input<aws.iam.Role>[]>`. I think this will crash if the outer Input is not resolved yet.

Comment (t0yv0) [reply nodejs/eks/authenticationMode.ts:49]: Great find! Let me rejigger this reinstanting some type discipline.

File: nodejs/eks/authenticationMode.ts [hunk 2]
```diff
@@ -64,6 +72,38 @@ export function validateAuthenticationMode(args: ClusterOptions) {
             }
         });
     }
+    return args;
+}
+
+// Validate promptly if possible, otherwise validate in the Promise chain underlying the Output and ensure that the
+// input is gated on the validation. Unfortunately since apply always unwraps, the validate function required here needs
+// to be able to handle both unwrapped and normal forms.
+function validatedInput<T>(
```
Comment (t0yv0) [inline nodejs/eks/authenticationMode.ts:81]: This trick didn't work as neatly as I hoped. I hoped to make a `pulumi.Input<T>` that is gated on the validation. Unfortunately I couldn't wrestle the jest framework to be able to assert against failing pulumi.Output values :/ so simply coercing `pulumi.Input<T>` to `pulumi.Output<T>` does not cut it because I couldn't fix the unit tests. Instead this is further refined to handle immediately available T on the stack and only jump into an apply chain if that is not possible. Unfortunately since apply always unwraps and there doesn't seem to be a non-unwrapping variant available, the `validate` function  has this signature:

```
 validate: (value: T|pulumi.Unwrap<T>|undefined) => void
```

where the ideal signature would be:

```
 validate: (value: T|undefined) => void
```

File: nodejs/eks/authenticationMode.test.ts [hunk 3]
```diff
@@ -70,10 +70,20 @@ describe("validateAuthenticationMode", () => {
         };
 
         expect(() => validateAuthenticationMode(args)).toThrowError(
-            "The 'instanceRoles' property is not supported when 'authenticationMode' is set to 'API'.",
+            "The 'instanceRoles' property does not support non-empty values when 'authenticationMode' is set to 'API'.",
```
Comment (t0yv0) [inline nodejs/eks/authenticationMode.test.ts:73]: Actually something must be of as this test shouldn't compile.

```
 const args = {
            authenticationMode: "API",
            instanceRoles: ["roleArn"],
        };
```

"roleArn" is not a valid aws.eks.Role.

**Comment by t0yv0** [comment]
Wish list for the Node SDK here.

- should be a simple way to assert that `Output<T>` values are failing in jest, such as transforming `Output<T>` to `Promise<OutputResult<T>>` and asserting that this promise resolves with an exception

- should be a way to apply `(x: T)=>U` to an `Output<T>` and receive `Output<U>` and not `Output<Unwrap<U>>` opting out of the unwrapping

File: nodejs/eks/authenticationMode.test.ts (hunk 3 above)
Comment (flostadler) [reply nodejs/eks/authenticationMode.test.ts:73]: The test isn't type checked it's executed as js. If you'd like to satisfy the type checker you could pass the `args as ClusterOptions`

File: nodejs/eks/authenticationMode.ts [hunk 4]
```diff
@@ -34,24 +35,31 @@ export function validateAuthenticationMode(args: ClusterOptions) {
...
-        "roleMappings",
-        "userMappings",
-        "instanceRoles",
-    ];
-    const apiOnlyProperties: (keyof ClusterOptions)[] = ["accessEntries"];
-
     if (!supportsConfigMap(args.authenticationMode)) {
-        configMapOnlyProperties.forEach((prop) => {
-            if (args[prop]) {
+        const check: (prop: string) => (propertyValue: any|undefined) => void = (prop) => (pv) => {
```
Comment (flostadler) [inline nodejs/eks/authenticationMode.ts:39]: Nit: `prop` could be `keyof ClusterOptions`. What do you think about renaming this to `checkIsUndefined`? That way it's clearer what it is actually checking

File: nodejs/eks/authenticationMode.ts [hunk 5]
```diff
@@ -34,24 +35,31 @@ export function validateAuthenticationMode(args: ClusterOptions) {
...
+            if (pv !== undefined) {
                 throw new Error(
                     `The '${prop}' property is not supported when 'authenticationMode' is set to '${args.authenticationMode}'.`,
                 );
             }
+        };
+
+        args.roleMappings = validatedInput(args.roleMappings, check("roleMappings"));
```
Comment (flostadler) [inline nodejs/eks/authenticationMode.ts:47]: Why don't we extend this to roleMappings and userMappings as well? Would be a nice improvement and it's a bit odd imho if roleMappings/userMappings don't allow empty arrays while instanceRoles  does

File: nodejs/eks/authenticationMode.test.ts [hunk 6]
```diff
@@ -70,10 +70,20 @@ describe("validateAuthenticationMode", () => {
...
         );
     });
 
+    it("should not throw an error for instanceRoles=[] when authentication mode is set to API", () => {
+        const args = {
+            authenticationMode: "API",
+            instanceRoles: [],
```
Comment (flostadler) [inline nodejs/eks/authenticationMode.test.ts:80]: Could we also test passing instanceRoles as a Promise and Output?

Comment (t0yv0) [reply nodejs/eks/authenticationMode.test.ts:80]: That'd be great but I was running into limitations that seem to make failing outputs un-testable. I can ask around for help.

Comment (flostadler) [reply nodejs/eks/authenticationMode.test.ts:80]: Might be worth adding an integration test tif that doesn't work

Comment (t0yv0) [reply nodejs/eks/authenticationMode.test.ts:80]: I filed https://github.com/pulumi/pulumi/issues/16665 - there's something odd, possibly a bug in Node SDK that makes it extra difficult. I'll look into an integration test.

File: nodejs/eks/authenticationMode.test.ts (hunk 3 above)
Comment (t0yv0) [reply nodejs/eks/authenticationMode.test.ts:84]: I've added it to tsconfig.json and fixed it up, it now is type-checked.

File: nodejs/eks/authenticationMode.ts (hunk 5 above)
Comment (t0yv0) [reply nodejs/eks/authenticationMode.ts]: Done.

File: nodejs/eks/authenticationMode.test.ts [hunk 7]
```diff
@@ -18,10 +18,21 @@ import {
...
 
+import {
+    ClusterOptions, AuthenticationMode
+} from "./cluster";
+
+import * as aws from "@pulumi/aws";
+
 describe("validateAuthenticationMode", () => {
+
+    const testRole: aws.iam.Role = (<any>{"arn": "testRole"});
```
Comment (flostadler) [inline nodejs/eks/authenticationMode.test.ts:29]: nice!

File: provider/provider_test.go [hunk 8]
```diff
@@ -89,6 +90,50 @@ func TestReportUpgradeCoverage(t *testing.T) {
 	providertest.ReportUpgradeCoverage(t)
 }
 
+func TestEksClusterInputValidations(t *testing.T) {
```
Comment (flostadler) [inline provider/provider_test.go:93]: Things is executed as part of the upgrade tests right now in CI. What do you think about moving it to it's own job?

**Review by flostadler — APPROVED** [review]
LGTM, just one comment about CI

File: provider/provider_test.go (hunk 8 above)
Comment (t0yv0) [reply provider/provider_test.go:93]: Hmm, interesting, I thought that we're trying to put tests that are not useful as examples to end-users now under `provider/*` instead of under `examples/*`, I can backlog cleaning this up.

Comment (t0yv0) [reply provider/provider_test.go:93]: https://github.com/pulumi/pulumi-eks/issues/1257
